name: Deploy to EC2

on:
  push:
    branches: [ "main", "feature/deployment" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build Go binary
        run: |
          go mod tidy
          go build -o app .

      - name: SSH to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
            cd /var/www/url-shortener
            if [ ! -d .git ]; then
              git clone ${{ secrets.GIT_REPO_URL }} repo
            fi

            cd repo
            git reset --hard
            git pull

            # If your main.go is in the root folder of repo
            go build -o ../app

            # Start / restart services
            docker-compose pull
            docker-compose up -d
            cd ..
            ./app
            sudo systemctl restart url-shortener
          EOF

