name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build Go binary
        run: |
          go mod tidy
          go build -o app .

      - name: SSH to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
            cd /var/www/url-shortener

            # Clone repo if not exists
            if [ ! -d repo/.git ]; then
              git clone ${{ secrets.GIT_REPO_URL }} repo
            fi

            cd repo
            git checkout main
            git reset --hard
            git pull

            # Build new binary to parent directory
            go build -o ../app

            # Restart the service
            sudo systemctl restart url-shortener
          EOF


