name: Deploy to EC2

on:
  push:
    branches: [ "main", "feature/deployment" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Go binary
        run: |
          go mod tidy
          go build -o app .

      - name: SSH to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/url-shortener/app'
      # - name: Add SSH Key
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # - name: Copy binary to EC2
      #   run: |
      #     scp -o StrictHostKeyChecking=no app ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/url-shortener/app

      # - name: Restart Go service on EC2
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      #       sudo systemctl restart url-shortener
      #       sudo systemctl status url-shortener --no-pager
      #     EOF
